name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable: PriceListConverter.exe
            artifact: windows
          - os: macos-latest
            executable: PriceListConverter
            artifact: macos
          - os: ubuntu-latest
            executable: PriceListConverter
            artifact: linux

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name=PriceListConverter main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PriceListConverter-${{ matrix.artifact }}
        path: dist/${{ matrix.executable }}

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.executable }}
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
